# Generated by Django 4.1.7 on 2023-07-26 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('bc641269-96b0-4fd4-a74f-1883b1f701e7'), primary_key=True, serialize=False)),
                ('name', models.CharField(default='chat<django.db.models.fields.UUIDField>', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
