# Generated by Django 4.1.7 on 2023-07-26 06:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='users',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e09c5656-a2ac-4987-8586-80ee35458b46'), primary_key=True, serialize=False),
        ),
    ]
