# Generated by Django 4.1.7 on 2023-04-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='covering_letter',
            field=models.TextField(default=''),
        ),
    ]
