# Generated by Django 4.1.7 on 2023-04-21 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0004_remove_jobpost_categories_jobpost_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='last_name',
        ),
    ]
