# Generated by Django 4.1.7 on 2023-04-21 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0005_remove_applicant_email_remove_applicant_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
