# Generated by Django 4.1.7 on 2023-07-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0008_alter_applicant_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.CharField(blank=True, choices=[('UnderConsideration', 'Underconsideration'), ('Denied', 'Denied'), ('Invited', 'Invited')], default='UnderConsideration', max_length=18, null=True),
        ),
    ]
